# Site settings
title: FRED's Backpack
email: fredsbackpack@gmail.com
description: A collections of tools and resources for new Front-end Developers
baseurl: ""
url: "http://fredsbackpack.com"
twitter_username: fredsbackpack
github_username:  poopsplat/fredsbackpack

# Build settings
markdown: kramdown
exclude: [node_modules]