# Site settings
title: FRED's Backpack
email: matt.m.soria@gmail.com
description: A collections of tools and resources for new Front-end Developers
baseurl: ""
url: "http://fredsbackpack.com"
twitter_username: poopsplat
github_username:  poopsplat

# Build settings
markdown: kramdown
exclude: [node_modules]